/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.datastructure.app;

public class App {
    public static void main(String[] args) {
        String a = "abc";
        System.out.println(a.substring(0, 1));
        System.out.println(a.substring(2));
    }
}
