/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.datastructure.app;

public class App {
    public static void main(String[] args) {
        long value = Integer.MAX_VALUE * 10L + 13213L;
        System.out.println(Long.hashCode(Long.MAX_VALUE- 500000000000L));
        System.out.println(Long.toBinaryString(Long.MAX_VALUE >>> 32));
        System.out.println(0b01101);
        System.out.println(Integer.toBinaryString(22));
    }
}